/**
 * What a theory is, and why the exam's true/false claims come out as they do.
 *
 * The membership tables are computed with `inTheory` over the same four
 * structures the game uses, so the answers here are decided rather than
 * recalled — including the two counterexamples, which are found by search.
 */

import { inTheory, modelsOf, subsetWitness, unionWitness, showFormula } from '@/logic'
import { Callout, GuideSection, Prose, Sym } from '@/ui/guide'
import { Card } from '@/ui/primitives'
import { FoText } from '@/ui/FoText'
import { WORLD, parse } from './theoryWorld'

const CATALOGUE = [
  '∀x:p(x)',
  '∃x:p(x)',
  '∀x:¬p(x)',
  '∃x:¬p(x)',
  '(∀x:p(x))→(∃x:p(x))',
  '(∀x:p(x))∨(∀x:¬p(x))',
].map((source) => ({ source, formula: parse(source) }))

const AXIOM_SETS = [['∀x:p(x)'], ['∃x:p(x)'], ['∃x:p(x)', '∃x:¬p(x)']]

function MembershipTable() {
  const columns = AXIOM_SETS.map((axioms) => ({
    axioms,
    models: modelsOf(WORLD, axioms.map(parse)),
  }))
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-left text-sm">
        <thead className="text-xs uppercase tracking-wider text-ink-soft">
          <tr>
            <th className="px-2 py-1">formula</th>
            {columns.map((column) => (
              <th key={column.axioms.join()} className="px-2 py-1 font-logic normal-case">
                {column.axioms.join(', ')}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {CATALOGUE.map((entry) => (
            <tr key={entry.source}>
              <td className="px-2 py-1">
                <FoText text={entry.source} className="font-bold" />
              </td>
              {columns.map((column) => (
                <td key={column.axioms.join()} className="px-2 py-1 font-bold">
                  {inTheory(WORLD, column.models, entry.formula) ? 'in' : '—'}
                </td>
              ))}
            </tr>
          ))}
          <tr>
            <td className="px-2 py-1 text-xs uppercase tracking-wider text-ink-soft">models</td>
            {columns.map((column) => (
              <td key={column.axioms.join()} className="px-2 py-1 font-logic text-xs">
                {column.models.map((index) => WORLD.labels[index]).join(' ')}
              </td>
            ))}
          </tr>
        </tbody>
      </table>
    </div>
  )
}

export function CloseItUpGuide() {
  const everything = CATALOGUE.map((entry) => entry.formula)

  // Every subset of a theory need not be a theory: take the theory of ∀x:p(x)
  // and keep only ∃x:p(x) from it — the kept formula still entails things the
  // subset has dropped.
  const wholeModels = modelsOf(WORLD, [parse('∀x:p(x)')])
  const subset = subsetWitness(WORLD, wholeModels, [parse('∀x:p(x)')], everything)

  // The union of two theories need not be closed.
  const left = modelsOf(WORLD, [parse('(∀x:p(x))∨(∀x:¬p(x))')])
  const right = modelsOf(WORLD, [parse('∃x:p(x)')])
  const union = unionWitness(WORLD, left, right, everything)

  return (
    <div className="flex flex-col gap-7">
      <GuideSection title="The definition">
        <Card>
          <Prose>
            <p>
              A <strong>theory</strong> (Definition 5.1) is a set of closed formulas that is closed
              under logical consequence: if T entails φ, then φ is already in T. Nothing else. Every
              exam claim about theories is that one sentence applied.
            </p>
            <p>
              The usual way to make one is to start with axioms A and take everything they entail.
              That set is automatically closed, and it is what "the theory generated by A" means.
            </p>
          </Prose>
        </Card>

        <Callout tone="tip" title="Models make it computable">
          <p>
            Instead of chasing entailments, look at models. A set of axioms picks out the structures
            satisfying it, and the theory it generates is everything true in <em>all</em> of them.
            Add an axiom and you lose structures but gain formulas — the two move in opposite
            directions, and that opposition explains all four set claims below.
          </p>
        </Callout>
      </GuideSection>

      <GuideSection title="Membership over four structures">
        <Card>
          <Prose>
            <p>
              With a universe of two elements and one unary predicate there are four structures in
              total. That is small enough to decide membership by inspection, and it is what the
              game is built on.
            </p>
          </Prose>
          <div className="mt-3">
            <MembershipTable />
          </div>
        </Card>
      </GuideSection>

      <GuideSection title="The exam claims, and why">
        <Card>
          <Prose>
            <ul className="mt-1 flex list-disc flex-col gap-2 pl-5">
              <li>
                <strong>Every subset of a theory is a theory — false.</strong> Drop a formula and
                the rest may still entail it, so the set is no longer closed.
                {subset !== null && (
                  <>
                    {' '}
                    Keeping only <Sym>∀x:p(x)</Sym> leaves out{' '}
                    <Sym>{showFormula(subset)}</Sym>, which it entails.
                  </>
                )}
              </li>
              <li>
                <strong>Every superset of a theory is a theory — false</strong>, for the same
                reason from the other side: add one formula and you must add everything it entails
                too.
              </li>
              <li>
                <strong>The set of all valid formulas is a theory — true.</strong> It is the theory
                generated by no axioms at all, and a consequence of valid formulas is valid.
              </li>
              <li>
                <strong>The intersection of two theories is a theory — true.</strong> Its models are
                the two model sets together, so it is generated by that class.
              </li>
              <li>
                <strong>The union of two theories need not be — true, it need not.</strong>{' '}
                {union !== null && (
                  <>
                    Both theories together entail <Sym>{showFormula(union)}</Sym>, and neither of
                    them contains it.
                  </>
                )}
              </li>
              <li>
                <strong>A theory with one false formula contains every formula.</strong> False here
                means false in every model, so it has no models, and then everything is vacuously
                entailed. That is what Definition 5.3 calls inconsistent.
              </li>
            </ul>
          </Prose>
        </Card>

        <Callout tone="warn" title="Finitely axiomatizable is not the same as finite">
          <p>
            A finitely axiomatizable theory has finitely many <em>axioms</em>. It still contains
            infinitely many formulas — its closure. The exam asks this one directly, and "contains
            only finitely many formulas" is never the right answer for a consistent theory.
          </p>
        </Callout>
      </GuideSection>
    </div>
  )
}
