/**
 * What a term order is for, and why "more general than" is not one.
 *
 * Every comparison shown is computed by the orders in `rewriting.ts` — the same
 * ones the game marks with.
 */

import {
  combinedOrder,
  moreGeneral,
  parseEquation,
  parseTerm,
  precedenceOrder,
  showTerm,
  sizeOrder,
  termVariables,
  type Signature,
} from '@/logic'
import { Callout, GuideSection, Prose, Sym } from '@/ui/guide'
import { Card } from '@/ui/primitives'
import { EquationText, TermText } from '@/ui/TermText'
import { legalAs } from './orientRules'

const SIG: Signature = { f: 2, g: 1, h: 1 }
const UNARY: Signature = { f: 1, g: 1, h: 1 }

export function OrientGuide() {
  return (
    <div className="flex flex-col gap-7">
      <GuideSection title="What a term order has to satisfy">
        <Card>
          <Prose>
            <p>Definition 3.20 asks for five things, and each one is there for a reason:</p>
            <ol className="flex list-decimal flex-col gap-1 pl-5">
              <li>Transitive, and</li>
              <li>never both ways round — so it is an order at all.</li>
              <li>
                <strong>Stable under substitution:</strong> <Sym>t ≻ t′</Sym> implies{' '}
                <Sym>σ(t) ≻ σ(t′)</Sym>. A rule is used on instances, so if the order flipped under
                substitution the rule could point uphill in practice.
              </li>
              <li>
                <strong>Stable under context:</strong> replacing a subterm by a bigger one makes the
                whole term bigger. A rule fires deep inside a term, so the same reason.
              </li>
              <li>
                <strong>No infinite descending chains.</strong> This is the one that makes reduction
                terminate.
              </li>
            </ol>
          </Prose>
        </Card>

        <Callout tone="warn" title="Why counting symbols alone is not a term order">
          <p>
            <Sym>g(x) ≻ y</Sym> by symbol count. Now apply <Sym>{'{y ↦ g(g(x))}'}</Sym>: the left
            side is unchanged and the right side becomes bigger, so the order has flipped. Condition
            3 fails.
          </p>
          <p className="mt-2">
            The repair is to also require that <strong>each variable occurs at least as often</strong>{' '}
            in the bigger term. Then a substitution adds at least as much to the bigger side as to
            the smaller, and the order survives.
          </p>
          <Comparisons
            rows={[
              ['g(x)', 'y'],
              ['f(x,y)', 'y'],
              ['f(f(x,y),x)', 'f(x,x)'],
              ['f(x,x)', 'f(y,y)'],
            ]}
          />
        </Callout>

        <Callout tone="warn" title="Why a symbol order alone is not one either">
          <p>
            Order the symbols and compare left to right, and you get{' '}
            <Sym>g(h(x)) ≻ g(g(h(x))) ≻ g(g(g(h(x)))) ≻ …</Sym> forever. Condition 5 fails.
          </p>
          <p className="mt-2">
            Combining the two fixes both: compare by size first, and only when that says nothing does
            the symbol order break the tie. That is the order this game uses.
          </p>
        </Callout>
      </GuideSection>

      <GuideSection title="The exam question: why “more general than” is not a term order">
        <Card>
          <Prose>
            <p>
              exam26bA asks exactly this about <Sym>t ≤ t′</Sym> — there is a σ with{' '}
              <Sym>σ(t) = t′</Sym>. It fails several conditions at once, and any one of them is a
              complete answer.
            </p>
            <ul className="mt-2 flex list-disc flex-col gap-2 pl-5 text-sm font-medium">
              <li>
                <strong>Infinite ascending — and so descending — chains.</strong>{' '}
                <Sym>x ≤ f(x) ≤ f(f(x)) ≤ …</Sym> never stops, so read as a reduction order it has
                no bottom. Condition 5.
              </li>
              <li>
                <strong>It is not antisymmetric.</strong> <Sym>f(x,y) ≤ f(y,x)</Sym> and{' '}
                <Sym>f(y,x) ≤ f(x,y)</Sym>, and they are different terms. Condition 2.
              </li>
              <li>
                <strong>It is not stable under substitution in the right direction.</strong> A
                substitution can only ever make a term more specific, so the relation is generated by
                exactly the operation the condition is about.
              </li>
            </ul>
          </Prose>
          <Generality />
        </Card>
      </GuideSection>

      <GuideSection title="The second condition on a rule">
        <Callout tone="tip" title="No fresh variables on the right">
          <p>
            <Sym>f(x,y) → z</Sym> is not a rule even if the order allows it: firing it would have to
            choose a term for <Sym>z</Sym> out of nowhere, and different choices would give different
            results from the same redex.
          </p>
          <p className="mt-2">
            So a rule may drop variables but never introduce them. This is easy to check and easy to
            forget.
          </p>
        </Callout>
        <Card>
          <Rules
            sources={['f(f(x,y),x)=f(x,x)', 'f(x,y)=z', 'g(x)=g(y)', 'g(h(x))=h(x)']}
          />
        </Card>
      </GuideSection>

      <GuideSection title="Playing it">
        <Card>
          <Prose>
            <ul className="flex list-disc flex-col gap-2 pl-5">
              <li>
                Three bins: point it left to right, right to left, or refuse it. Every question has
                at least one of each.
              </li>
              <li>
                Refuse for either reason — the two terms do not compare, or the smaller side has a
                variable the bigger one lacks. Afterwards each equation is annotated with which it
                was.
              </li>
              <li>
                The tie-break order is printed at the top and changes with the question, so it is
                worth reading rather than assuming.
              </li>
            </ul>
          </Prose>
        </Card>
      </GuideSection>
    </div>
  )
}

/** Size order against the symbol order, side by side. */
function Comparisons({ rows }: { rows: [string, string][] }) {
  const combined = combinedOrder(['f', 'g', 'h'])
  const lex = precedenceOrder(['f', 'g', 'h'])
  return (
    <div className="mt-3 overflow-x-auto">
      <table className="w-full border-collapse text-left text-sm">
        <thead>
          <tr className="border-b-3 border-ink">
            <th className="py-2 pr-3 whitespace-nowrap">t</th>
            <th className="py-2 pr-3 whitespace-nowrap">t′</th>
            <th className="py-2 pr-3 whitespace-nowrap">by size</th>
            <th className="py-2 pr-3 whitespace-nowrap">by symbols</th>
            <th className="py-2">combined</th>
          </tr>
        </thead>
        <tbody>
          {rows.map(([left, right]) => {
            const one = parseTerm(left, SIG)
            const two = parseTerm(right, SIG)
            return (
              <tr key={`${left}|${right}`} className="border-t-2 border-dashed border-card-shade">
                <td className="py-2 pr-3 whitespace-nowrap">
                  <TermText term={one} className="font-bold" />
                </td>
                <td className="py-2 pr-3 whitespace-nowrap">
                  <TermText term={two} className="font-bold" />
                </td>
                <td className="py-2 pr-3 text-ink-soft">{sizeOrder.compare(one, two)}</td>
                <td className="py-2 pr-3 text-ink-soft">{lex.compare(one, two)}</td>
                <td className="py-2 font-bold">{combined.compare(one, two)}</td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

/** "More general than" going both ways at once. */
function Generality() {
  const one = parseTerm('f(x,y)', SIG)
  const two = parseTerm('f(y,x)', SIG)
  const chain = ['x', 'f(x,x)', 'f(f(x,x),f(x,x))'].map((source) => parseTerm(source, SIG))

  return (
    <div className="mt-3 rounded-xl bg-card-shade px-3 py-2 text-sm font-medium">
      <p className="flex flex-wrap items-baseline gap-2">
        <TermText term={one} className="font-bold" />
        <span>≤</span>
        <TermText term={two} className="font-bold" />
        <span className="font-bold text-space-red">{moreGeneral(one, two) ? 'yes' : 'no'}</span>
        <span className="opacity-60">and</span>
        <TermText term={two} className="font-bold" />
        <span>≤</span>
        <TermText term={one} className="font-bold" />
        <span className="font-bold text-space-red">{moreGeneral(two, one) ? 'yes' : 'no'}</span>
      </p>
      <p className="mt-2">
        And the chain never ends: {chain.map(showTerm).join(' ≤ ')} ≤ …
      </p>
    </div>
  )
}

/** Each equation judged for both conditions. */
function Rules({ sources }: { sources: string[] }) {
  const order = combinedOrder(['f', 'g', 'h'])
  return (
    <div className="mt-2 overflow-x-auto">
      <table className="w-full border-collapse text-left text-sm">
        <thead>
          <tr className="border-b-3 border-ink">
            <th className="py-2 pr-3 whitespace-nowrap">Equation</th>
            <th className="py-2 pr-3 whitespace-nowrap">As a rule</th>
            <th className="py-2">Why</th>
          </tr>
        </thead>
        <tbody>
          {sources.map((source) => {
            const signature = source.includes('f(') && source.includes(',') ? SIG : UNARY
            const equation = parseEquation(source, signature)
            const forward = legalAs(order, equation.left, equation.right)
            const backward = legalAs(order, equation.right, equation.left)
            const fresh = termVariables(equation.right).filter(
              (name) => !termVariables(equation.left).includes(name),
            )
            return (
              <tr key={source} className="border-t-2 border-dashed border-card-shade align-top">
                <td className="py-2 pr-3 whitespace-nowrap">
                  <EquationText left={equation.left} right={equation.right} className="font-bold" />
                </td>
                <td
                  className={`py-2 pr-3 font-bold ${
                    forward || backward ? 'text-grass-deep' : 'text-space-red'
                  }`}
                >
                  {forward ? 'l → r' : backward ? 'r → l' : 'neither'}
                </td>
                <td className="py-2 text-ink-soft">
                  {forward || backward
                    ? 'bigger side first, and no new variable'
                    : fresh.length > 0
                      ? `${fresh.join(', ')} appears only on the right`
                      : `${order.compare(equation.left, equation.right)} in this order`}
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}
