/**
 * Claims about ⊢ and ⊨ — ln.pdf §5.2, Exercise 11 question 1.
 *
 * Soundness ("provable implies true") and completeness ("true implies
 * provable") are separate properties pointing in opposite directions, and the
 * exam's list mixes them with Gödel's theorem to see whether they are being
 * told apart. Every claim here carries the reason it falls where it does.
 */

import type { Claim } from './claimSort'

export type ProvabilityBin = 'true' | 'false'

export const PROVABILITY_CLAIMS: readonly Claim<ProvabilityBin>[] = [
  {
    id: 'sound',
    text: 'Every provable formula is true.',
    bin: 'true',
    why: 'Soundness. A calculus that could prove something false would be worthless, and the resolution calculus of Chapter 4 is proved sound.',
    difficulty: ['easy', 'medium'],
  },
  {
    id: 'complete-fo',
    text: 'Every valid first-order formula is provable.',
    bin: 'true',
    why: "Gödel's completeness theorem — a different theorem from the incompleteness one, and about the calculus rather than about arithmetic.",
    difficulty: ['medium', 'hard'],
  },
  {
    id: 'complete-nat-plus',
    text: 'Every formula in T(ℕ,=,+) can be proven.',
    bin: 'true',
    why: 'Presburger arithmetic is decidable and axiomatizable, so its truths are exactly its theorems. Adding multiplication is what breaks this.',
    difficulty: ['medium', 'hard'],
  },
  {
    id: 'complete-nat-times',
    text: 'Every formula in T(ℕ,=,+,*) can be proven from a computable set of axioms.',
    bin: 'false',
    why: "Gödel's first incompleteness theorem. Any computable, consistent axiom set for arithmetic leaves a true sentence unproved.",
    difficulty: ['medium', 'hard'],
  },
  {
    id: 'true-implies-provable',
    text: 'Every true formula is provable.',
    bin: 'false',
    why: 'True in which structure? Truth in ℕ is not provability, and that gap is exactly incompleteness.',
    difficulty: ['easy', 'medium'],
  },
  {
    id: 'decidable-provable',
    text: 'If a theory is decidable, every formula in it is provable.',
    bin: 'false',
    why: 'Decidable means membership can be *computed*; it says nothing about a proof calculus, and a theory need not be axiomatizable at all.',
    difficulty: ['hard'],
  },
  {
    id: 'consistent-no-contradiction',
    text: 'A consistent theory cannot contain both φ and ¬φ.',
    bin: 'true',
    why: 'Containing both would make it contain everything, since a contradiction entails anything — and that is what inconsistent means.',
    difficulty: ['easy'],
  },
  {
    id: 'complete-decides',
    text: 'A complete theory contains φ or ¬φ for every closed φ.',
    bin: 'true',
    why: 'That is Definition 5.3 of complete, word for word.',
    difficulty: ['easy'],
  },
  {
    id: 'unprovable-means-false',
    text: 'If a formula cannot be proven, its negation can.',
    bin: 'false',
    why: 'Only in a complete theory. In general both a formula and its negation can be out of reach — which is what an incomplete theory is.',
    difficulty: ['medium', 'hard'],
  },
  {
    id: 'proof-search-terminates',
    text: 'There is an algorithm deciding whether a first-order formula is valid.',
    bin: 'false',
    why: "Church and Turing: validity is only semi-decidable. Proofs of valid formulas can be enumerated, but nothing halts on the invalid ones.",
    difficulty: ['hard'],
  },
  {
    id: 'valid-is-theory',
    text: 'The set of all valid formulas is a theory.',
    bin: 'true',
    why: 'It is the theory generated by no axioms, and a consequence of valid formulas is valid.',
    difficulty: ['easy', 'medium'],
  },
]
