/**
 * Consistent, complete, or neither — ln.pdf §5.1, Definition 5.3, and the
 * true/false questions on exam26a and exam26bA.
 *
 * Two properties, and both are statements about the theory's models.
 *
 *   Consistent   it has a model. An inconsistent theory contains every
 *                formula, including ⊥, which is what exam26bA's "the theory
 *                generated by {∀x:p(x), ∃x:¬p(x)} is inconsistent" is about.
 *   Complete     it decides every closed formula: φ or ¬φ is in it. Over a
 *                class of structures that is exactly "all its models agree",
 *                so a formula two of its models disagree about is a witness
 *                that it is not.
 *
 * Saying "incomplete" is cheap; producing the formula it fails to decide is
 * not, so the game asks for it. That witness is checked, not compared against
 * a stored answer — any formula the theory neither contains nor refutes is
 * accepted.
 */

import { useEffect, useMemo, useState } from 'react'
import { completenessWitness, inTheory, isConsistent, modelsOf, showFormula } from '@/logic'
import { defineMinigame } from '@/engine/registry'
import type { Difficulty, GenerateContext, MinigameScreenProps, Verdict } from '@/engine/types'
import { Button, Card } from '@/ui/primitives'
import { FoText } from '@/ui/FoText'
import { MovingItem, MovingList, Pop } from '@/ui/motion'
import { CATALOGUE, CATALOGUE_FORMULAS, WORLD, parse } from './theoryWorld'
import { TheoryPropertiesGuide } from './theoryProperties.guide'

export interface PropertiesQuestion {
  axioms: string[]
  /** Formulas offered as the undecided witness. */
  bank: string[]
}

export interface PropertiesAnswer {
  consistent: boolean
  complete: boolean
  /** Required only when the claim is "incomplete". */
  witness: string | null
}

export const modelsOfQuestion = (question: PropertiesQuestion): number[] =>
  modelsOf(WORLD, question.axioms.map(parse))

/** A formula the theory neither contains nor refutes. */
export function undecided(question: PropertiesQuestion, source: string): boolean {
  const models = modelsOfQuestion(question)
  const formula = parse(source)
  return (
    !inTheory(WORLD, models, formula) &&
    !inTheory(WORLD, models, { kind: 'not', body: formula })
  )
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

const AXIOM_SETS: Record<Difficulty, readonly string[][]> = {
  easy: [
    ['∀x:p(x)'],
    ['∀x:¬p(x)'],
    ['∃x:p(x)'],
    ['∀x:p(x)', '∃x:¬p(x)'],
  ],
  medium: [
    ['∃x:p(x)', '∃x:¬p(x)'],
    ['(∀x:p(x))∨(∀x:¬p(x))'],
    ['∃x:¬p(x)'],
    ['∃x:(p(x)∧¬p(x))'],
    ['∀x:p(x)', '∀x:¬p(x)'],
  ],
  hard: [
    ['(∃x:p(x))→(∀x:p(x))'],
    ['∀x:(p(x)∨¬p(x))'],
    ['(∀x:p(x))→(∃x:¬p(x))'],
    ['∃x:p(x)', '(∃x:p(x))→(∀x:p(x))'],
    ['(∃x:p(x))∧(∃x:¬p(x))', '∀x:p(x)'],
  ],
}

function generate({ rng, difficulty }: GenerateContext): PropertiesQuestion {
  const axioms = [...rng.pick([...AXIOM_SETS[difficulty]])]
  // The bank always offers a genuine witness when one exists, plus formulas
  // the theory does decide — otherwise picking any chip would work.
  const bank = rng.shuffle(CATALOGUE.filter((source) => !axioms.includes(source))).slice(0, 6)
  const question = { axioms, bank }
  const models = modelsOfQuestion(question)
  const needed = completenessWitness(WORLD, models, CATALOGUE_FORMULAS)

  if (needed !== null && !bank.some((source) => undecided(question, source))) {
    return { axioms, bank: rng.shuffle([showFormula(needed), ...bank.slice(0, 5)]) }
  }
  return question
}

// ---------------------------------------------------------------------------
// Marking
// ---------------------------------------------------------------------------

function solve(question: PropertiesQuestion): PropertiesAnswer {
  const models = modelsOfQuestion(question)
  const witness = completenessWitness(WORLD, models, CATALOGUE_FORMULAS)
  const consistent = isConsistent(models)
  return {
    consistent,
    complete: consistent && witness === null,
    witness: witness === null ? null : (question.bank.find((source) => undecided(question, source)) ?? showFormula(witness)),
  }
}

function check(question: PropertiesQuestion, answer: PropertiesAnswer): Verdict {
  const wanted = solve(question)
  const models = modelsOfQuestion(question)

  if (answer.consistent !== wanted.consistent) {
    return {
      correct: false,
      message: 'Count the structures satisfying every axiom',
      score: 0,
      detail:
        'Consistent means having at least one model. An inconsistent theory has none, and then it contains every formula at once — including ⊥.',
    }
  }

  if (answer.complete !== wanted.complete) {
    return {
      correct: false,
      message: 'Two models that disagree about a formula make it incomplete',
      score: 0.25,
      detail:
        'A complete theory decides every closed formula. If two of its models give a formula different truth values, neither the formula nor its negation is in the theory.',
    }
  }

  if (!wanted.complete && wanted.consistent) {
    if (answer.witness === null) {
      return {
        correct: false,
        message: 'An incompleteness claim needs the formula it fails to decide',
        score: 0.4,
        detail: 'Find a formula that some model satisfies and another does not.',
      }
    }
    if (!undecided(question, answer.witness)) {
      return {
        correct: false,
        // Never say which one would work.
        message: 'The theory does decide that one',
        score: 0.4,
        detail:
          'A witness has to be true in some model of the axioms and false in another. If every model agrees, the theory contains it or contains its negation.',
      }
    }
  }

  return {
    correct: true,
    message: !wanted.consistent
      ? 'No models — inconsistent, and it contains everything'
      : wanted.complete
        ? 'One model up to what the language can say — complete'
        : 'Consistent, and undecided about that formula',
    detail: `The axioms hold in ${models.map((index) => WORLD.labels[index]).join(', ') || 'no structure at all'}.`,
  }
}

// ---------------------------------------------------------------------------
// Screen
// ---------------------------------------------------------------------------

function Toggle({
  label,
  yes,
  value,
  onChange,
  locked,
}: {
  label: string
  yes: string
  value: boolean | null
  onChange: (value: boolean) => void
  locked: boolean
}) {
  return (
    <div className="tile bg-card-shade px-3 py-2">
      <p className="text-xs font-bold uppercase tracking-wider text-ink-soft">{label}</p>
      <div className="mt-1 grid grid-cols-2 gap-1.5">
        <Button
          variant={value === true ? 'coin' : 'secondary'}
          disabled={locked}
          onClick={() => onChange(true)}
          className="!min-h-10 !px-2 !text-sm"
        >
          {yes}
        </Button>
        <Button
          variant={value === false ? 'coin' : 'secondary'}
          disabled={locked}
          onClick={() => onChange(false)}
          className="!min-h-10 !px-2 !text-sm"
        >
          not {yes}
        </Button>
      </div>
    </div>
  )
}

function Screen({
  question,
  submit,
  locked,
}: MinigameScreenProps<PropertiesQuestion, PropertiesAnswer>) {
  const [consistent, setConsistent] = useState<boolean | null>(null)
  const [complete, setComplete] = useState<boolean | null>(null)
  const [witness, setWitness] = useState<string | null>(null)
  const wanted = useMemo(() => solve(question), [question])

  useEffect(() => {
    setConsistent(null)
    setComplete(null)
    setWitness(null)
  }, [question])

  const ready =
    consistent !== null &&
    complete !== null &&
    (complete || !consistent || witness !== null)

  return (
    <Card>
      <p className="text-sm font-semibold uppercase tracking-widest text-ink-soft">
        Name the properties
      </p>

      <p className="mt-2 text-xs font-bold uppercase tracking-wider text-ink-soft">
        The theory generated by
      </p>
      <div className="mt-1 flex flex-col gap-1">
        {question.axioms.map((axiom) => (
          <div key={axiom} className="tile bg-coin px-3 py-1.5">
            <FoText text={axiom} className="text-base font-bold" />
          </div>
        ))}
      </div>
      <p className="mt-1 text-xs font-medium text-ink-soft">
        over the four structures on {'{1,2}'} — {WORLD.labels.join(', ')}
      </p>

      <div className="mt-3 grid gap-2 sm:grid-cols-2">
        <Toggle
          label="Does it have a model?"
          yes="consistent"
          value={consistent}
          onChange={setConsistent}
          locked={locked}
        />
        <Toggle
          label="Does it decide every formula?"
          yes="complete"
          value={complete}
          onChange={setComplete}
          locked={locked}
        />
      </div>

      {complete === false && consistent === true && !locked && (
        <>
          <p className="mt-3 text-xs font-bold uppercase tracking-wider text-ink-soft">
            Then show the formula it cannot decide
          </p>
          <MovingList className="mt-1 flex flex-wrap gap-1.5">
            {question.bank.map((source) => (
              <MovingItem
                key={source}
                id={source}
                onClick={() => setWitness(source)}
                className={`tile px-2.5 py-1 ${witness === source ? 'bg-grass text-white' : 'bg-card'}`}
              >
                <FoText text={source} className="text-sm font-bold" />
              </MovingItem>
            ))}
          </MovingList>
        </>
      )}

      {locked && (
        <Pop className="mt-3 rounded-2xl bg-card-shade p-3 text-sm font-medium text-ink-soft">
          Models: {modelsOfQuestion(question).map((index) => WORLD.labels[index]).join(', ') || 'none'}
          {wanted.witness !== null && (
            <>
              {' '}— and <span className="font-logic font-bold text-ink">{wanted.witness}</span> is
              left undecided.
            </>
          )}
        </Pop>
      )}

      {!locked && (
        <Button
          variant="coin"
          className="mt-3 w-full"
          disabled={!ready}
          onClick={() =>
            submit({
              consistent: consistent === true,
              complete: complete === true,
              witness,
            })
          }
        >
          {ready ? 'Submit' : 'Answer both first'}
        </Button>
      )}
    </Card>
  )
}

export const theoryPropertiesGame = defineMinigame<PropertiesQuestion, PropertiesAnswer>({
  id: 'theory-properties',
  title: 'Name The Property',
  tagline: 'Consistent? Complete? And if not complete, show what it cannot decide.',
  topics: ['theories'],
  icon: '🏷️',
  roundSeconds: 150,
  sprintQuestions: 8,
  // Two booleans is four guesses, and a wrong guess costs almost nothing
  // without this — the witness is the only part that cannot be guessed.
  sprintPenaltySeconds: 8,
  generate,
  check,
  solve,
  questionKey: (question) => question.axioms.join('∧'),
  explain: (question) => {
    const answer = solve(question)
    return answer.consistent
      ? answer.complete
        ? 'Every model of the axioms agrees on every formula, so the theory is complete.'
        : `The models disagree about ${answer.witness}, so the theory decides neither it nor its negation.`
      : 'The axioms have no model, so the theory contains every formula — inconsistent.'
  },
  Screen,
  Guide: TheoryPropertiesGuide,
})
