/**
 * Set operations on theories.
 *
 * The counterexamples are found by `unionWitness` over the four structures the
 * games use, so the page shows what the search actually returns — nothing here
 * is a remembered example.
 */

import { inTheory, modelsOf, unionClosureModels, unionWitness, showFormula } from '@/logic'
import { Callout, GuideSection, Prose, Sym } from '@/ui/guide'
import { Card } from '@/ui/primitives'
import { FoText } from '@/ui/FoText'
import { CATALOGUE_FORMULAS, WORLD, parse } from './theoryWorld'

const PAIRS: readonly [string[], string[]][] = [
  [['∃x:p(x)'], ['∃x:¬p(x)']],
  [['∀x:p(x)'], ['∃x:p(x)']],
  [['(∀x:p(x))∨(∀x:¬p(x))'], ['∃x:p(x)']],
]

function UnionTable() {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-left text-sm">
        <thead className="text-xs uppercase tracking-wider text-ink-soft">
          <tr>
            <th className="px-2 py-1">T₁</th>
            <th className="px-2 py-1">T₂</th>
            <th className="px-2 py-1">models of both</th>
            <th className="px-2 py-1">breaks the union</th>
          </tr>
        </thead>
        <tbody>
          {PAIRS.map(([left, right]) => {
            const leftModels = modelsOf(WORLD, left.map(parse))
            const rightModels = modelsOf(WORLD, right.map(parse))
            const witness = unionWitness(WORLD, leftModels, rightModels, CATALOGUE_FORMULAS)
            return (
              <tr key={`${left.join()}|${right.join()}`} className="align-top">
                <td className="px-2 py-1">
                  <FoText text={left.join(', ')} className="font-bold" />
                </td>
                <td className="px-2 py-1">
                  <FoText text={right.join(', ')} className="font-bold" />
                </td>
                <td className="px-2 py-1 font-logic text-xs">
                  {unionClosureModels(leftModels, rightModels)
                    .map((index) => WORLD.labels[index])
                    .join(' ') || '—'}
                </td>
                <td className="px-2 py-1 font-logic font-bold">
                  {witness === null ? 'nothing — it is closed' : showFormula(witness)}
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

export function UnionTroubleGuide() {
  const left = modelsOf(WORLD, [parse('∃x:p(x)')])
  const right = modelsOf(WORLD, [parse('∃x:¬p(x)')])
  const witness = unionWitness(WORLD, left, right, CATALOGUE_FORMULAS)

  return (
    <div className="flex flex-col gap-7">
      <GuideSection title="Fewer models, more formulas">
        <Card>
          <Prose>
            <p>
              Every question about combining theories is easier through their models. A theory's
              models are the structures satisfying all of it, and a formula is in the theory exactly
              when all of them make it true. So the two directions are opposite: adding axioms
              removes models and adds formulas.
            </p>
            <ul className="mt-2 flex list-disc flex-col gap-1 pl-5">
              <li>
                <Sym>T₁ ⊆ T₂</Sym> exactly when <Sym>models(T₂) ⊆ models(T₁)</Sym>.
              </li>
              <li>
                <Sym>T₁ ∩ T₂</Sym> is a theory — the one whose models are both model sets together.
              </li>
              <li>
                <Sym>T₁ ∪ T₂</Sym> need not be. What the two entail together is what the structures
                modelling <em>both</em> satisfy, and that can be strictly more than either theory
                contains.
              </li>
            </ul>
          </Prose>
        </Card>

        <Callout tone="tip" title="The standard counterexample">
          {witness === null ? (
            <p>Every pair in this little world happens to be closed.</p>
          ) : (
            <p>
              Take <Sym>T₁</Sym> generated by <Sym>∃x:p(x)</Sym> and <Sym>T₂</Sym> by{' '}
              <Sym>∃x:¬p(x)</Sym>. Together they entail <Sym>{showFormula(witness)}</Sym>, and
              neither one contains it —{' '}
              {inTheory(WORLD, left, witness) ? 'though the first does' : 'the first does not'}, and{' '}
              {inTheory(WORLD, right, witness) ? 'the second does' : 'neither does the second'}. The
              union is therefore not closed, and so not a theory.
            </p>
          )}
        </Callout>
      </GuideSection>

      <GuideSection title="Three pairs, decided">
        <Card>
          <UnionTable />
          <Prose>
            <p className="mt-3">
              The middle row is the case that saves the claim from being about every union: when one
              theory contains the other, the union is the bigger one, and that is closed. "Need not
              be a theory" is the exact wording, and it is exact on purpose.
            </p>
          </Prose>
        </Card>

        <Callout tone="warn" title="Subsets and supersets fail for the same reason">
          <p>
            Take formulas away and the rest may still entail them. Add formulas and you owe their
            consequences too. Neither operation respects closure, which is why both exam claims
            about them are false — and it is the same one sentence, read in two directions.
          </p>
        </Callout>
      </GuideSection>
    </div>
  )
}
